-- MSSV: 21127511
-- MALOP: 21CLC02

USE QLDTAI

-- SUM(SỐ)
-- AVG(SỐ) 
-- MIN, MAX(BẤT KỲ)
-- COUNT(*): ĐẾM DÒNG
-- COUNT(MABM): ĐẾM GTRI KHÁC NULL
-- COUNT(DISTINCT MABM): ĐẾM GIÁ TRỊ KHÔNG TRÙNG KO NULL

-- CHO BIET NĂM SINH VÀ SO LUONG GV SINH TRONG NĂM ĐÓ

-- SELECT YEAR(NGSINH) 'NĂM SINH', MONTH(GV.NGSINH) 'THÁNG SINH', COUNT(*) 'SỐ LƯỢNG'
-- FROM GIAOVIEN GV
-- GROUP BY YEAR(GV.NGSINH), MONTH(GV.NGSINH)
-- HAVING COUNT(*) > 1


-- Q27: CHO BIẾT SỐ LƯỢNG GIÁO VIÊN VÀ TỔNG LƯƠNG CỦA HỌ

SELECT COUNT(*) 'SỐ LƯỢNG GV', SUM(LUONG) 'TỔNG LƯƠNG'
FROM GIAOVIEN GV

-- Q28: CHO BIẾT SỐ LƯỢNG GIÁO VIÊN VÀ LƯƠNG TB CỦA TƯNG BỘ MÔN

SELECT BM.MABM AS 'TÊN BỘ MÔN', COUNT(MAGV) AS 'SỐ LƯỢNG GV', AVG(GV.LUONG) AS 'LƯƠNG TB'
FROM GIAOVIEN GV RIGHT JOIN BOMON BM
ON GV.MABM = BM.MABM
GROUP BY BM.MABM

-- Q29: CHO BIẾT TÊN CHỦ ĐỀ VÀ SỐ LƯỢNG ĐỀ TÀI THUỘC VỀ CHỦ ĐỀ ĐÓ

SELECT CD.TENCD AS 'TÊN CHỦ ĐỀ', COUNT(DT.MADT) AS 'SỐ LƯỢNG ĐỀ TÀI'
FROM ChuDe CD JOIN DeTai DT 
ON CD.MACD = Dt.MACD
GROUP BY CD.TENCD;

-- Q30: CHO BIẾT TÊN GIÁO VIÊN VÀ SỐ LƯỢNG ĐỀ TÀI MÀ GIÁO VIÊN ĐÓ THAM GIA

SELECT GV.HOTEN AS 'TÊN GIÁO VIÊN', COUNT(TGDT.MADT) AS 'SỐ LƯỢNG ĐỀ TÀI THAM GIA'
FROM GIAOVIEN GV JOIN THAMGIADT TGDT
ON GV.MAGV = TGDT.MAGV
GROUP BY GV.HOTEN

--SELECT * FROM THAMGIADT
--SELECT * FROM GIAOVIEN

-- Q31 : CHO BIẾT TÊN GIÁO VIÊN VÀ SỐ LƯỢNG ĐỀ TÀI MÀ GIÁO VIÊN ĐÓ LÀM CHỦ NHIỆM

SELECT GV.HOTEN AS 'TÊN GIÁO VIÊN', COUNT(DT.MADT) AS 'SỐ LƯỢNG ĐỀ TÀI CHỦ NHIỆM'
FROM GIAOVIEN GV JOIN DETAI DT
ON GV.MAGV = DT.GVCNDT
GROUP BY GV.HOTEN

-- Q32: VỚI MỖI GIÁO VIÊN CHO TÊN GIÁO VIÊN VÀ SỐ NGƯỜI THÂN CỦA GIÁO VIÊN ĐÓ

SELECT GV.HOTEN AS 'TÊN GIÁO VIÊN', COUNT(NT.MAGV) AS 'SỐ NGƯỜI THÂN'
FROM GIAOVIEN GV JOIN NGUOITHAN NT
ON GV.MAGV = NT.MAGV
GROUP BY GV.HOTEN

-- Q33: CHO BIẾT TÊN NHỮNG GIÁO VIÊN ĐÃ THAM GIA TỪ 3 ĐỀ TÀI TRỞ LÊN

SELECT GV.HOTEN AS 'TÊN GIÁO VIÊN', COUNT(TGDT.MADT) AS 'SỐ LƯỢNG ĐỀ TÀI THAM GIA'
FROM GIAOVIEN GV LEFT JOIN THAMGIADT TGDT
ON GV.MAGV = TGDT.MAGV
GROUP BY GV.HOTEN
HAVING COUNT(TGDT.MADT) > 2

-- Q34: CHO BIẾT SỐ LƯỢNG GIÁO VIÊN ĐÃ THAM GIA ĐỀ TÀI ỨNG DỤNG HÓA HỌC XANH

SELECT COUNT(TGDT.MAGV) AS 'SỐ LƯỢNG'
FROM DETAI DT LEFT JOIN THAMGIADT TGDT
ON DT.MADT = TGDT.MADT
WHERE DT.TENDT = N'Ứng dụng hóa học xanh'
GROUP BY DT.MADT

