-- MSSV: 21127511
-- MALOP: 21CLC02

USE master
GO

USE QLDTAI

--PHÉP CHIA
--NHẬN DẠNG: TẤT CẢ DÒNG TRONG BẢNG GÌ ĐÓ ~ TẬP CHIA
--XÁC ĐỊNH THÀNH PHẦN
--KQUA: DỮ LIỆU CẦN XUẤT RA (THUỘC TÍNH XÁC ĐỊNH DỮ LIỆU)
--CHIA: DỮ LIỆU CHIA (THUỘC TÍNH XÁC ĐỊNH 1 DÒNG)
--BICHIA: DỮ LIỆU TỔNG HỢP CỦA KQUA X CHIA

-- 58: CHO BIẾT TÊN GIÁO VIÊN NÀO MÀ THAM GIA ĐỀ TÀI ĐỦ TẤT CẢ CÁC CHỦ ĐỀ
--CÁCH 1: NOT EXISTS - EXCEPT
SELECT KQ.HOTEN 
FROM GIAOVIEN KQ
WHERE NOT EXISTS (SELECT C.MAGV
				  FROM THAMGIADT C
				  EXCEPT
				  SELECT BC.MAGV
				  FROM THAMGIADT BC, DETAI DT
				  WHERE DT.MADT = BC.MADT AND KQ.MAGV = BC.MAGV)

--59: CHO BIẾT TÊN ĐỀ TÀI ĐƯỢC TẤT CẢ GV HTTT THAM GIA
--KQ:DETAI (MADT)
--C: GIAOVIEN (MAGV)
--BC:THAMGIADT(MAGV,MADT)
--CÁCH 1: NOT EXISTS - EXCEPT
SELECT KQ.*
FROM DETAI KQ
WHERE NOT EXISTS (SELECT C.MAGV
				  FROM GIAOVIEN C
				  WHERE C.MABM = 'HTTT'
				  EXCEPT
				  SELECT BC.MAGV
				  FROM THAMGIADT BC
				  WHERE BC.MADT = KQ.MADT)
--CÁCH 2: NOT EXISTS - NOT EXISTS
SELECT KQ.*
FROM DETAI KQ
WHERE NOT EXISTS (SELECT *
				  FROM GIAOVIEN C
				  WHERE NOT EXISTS (SELECT *
								    FROM THAMGIADT BC
								    WHERE BC.MADT = KQ.MADT
									AND BC.MAGV = C.MAGV)
					AND C.MABM = 'HTTT'
				)
--CÁCH 3: HAVING - COUNT
SELECT KQ.MADT,COUNT(DISTINCT MAGV)
FROM DETAI KQ JOIN THAMGIADT BC ON BC.MADT = KQ.MADT
WHERE BC.MAGV IN (SELECT MAGV 
				  FROM GIAOVIEN C
				  WHERE C.MABM = 'HTTT')
GROUP BY KQ.MADT
HAVING COUNT(DISTINCT MAGV) = (SELECT COUNT(*)
								FROM GIAOVIEN C
								WHERE C.MABM = 'HTTT')

-- 60: CHO BIẾT TÊN ĐỀ TÀI CÓ TẤT CẢ GIẢNG VIÊN BỘ MÔN "HỆ THỐNG THÔNG TIN" THAM GIA

--CÁCH 1: NOT EXISTS - EXCEPT
SELECT KQ.*
FROM DETAI KQ
WHERE NOT EXISTS (SELECT C.MAGV
				  FROM GIAOVIEN C, BOMON BM
				  WHERE BM.TENBM = N'Hệ thống thông tin' AND BM.MABM = C.MABM
				  EXCEPT
				  SELECT BC.MAGV
				  FROM THAMGIADT BC
				  WHERE BC.MADT = KQ.MADT)

-- 61: CHO BIẾT GIÁO VIÊN NÀO ĐÃ THAM GIA TẤT CẢ CÁC ĐỀ TÀI CÓ MÃ CHỦ ĐỀ LÀ QLGD
--CÁCH 1: NOT EXISTS - EXCEPT
SELECT KQ.MAGV
FROM GIAOVIEN KQ
WHERE NOT EXISTS (SELECT DISTINCT TGDT.MAGV
				  FROM DETAI C, THAMGIADT TGDT
				  WHERE C.MACD = 'QLGD'
				  EXCEPT
				  SELECT BC.MAGV
				  FROM THAMGIADT BC
				  WHERE BC.MAGV = KQ.MAGV)

-- 62: CHO BIẾT TÊN GV NÀO THAM GIA TẤT CẢ CÁC ĐỀ TÀI MÀ GIÁO VIÊN TRẦN HÀ HƯƠNG ĐÃ THAM GIA

SELECT KQ.*
FROM GIAOVIEN KQ
WHERE NOT EXISTS (  
SELECT* FROM (
SELECT DISTINCT GV2.MAGV, TGDT.MADT
					FROM GIAOVIEN GV, THAMGIADT TGDT, GIAOVIEN GV2
					WHERE GV.HOTEN = N'Trần Hà Hương' AND TGDT.MAGV = GV.MAGV
					EXCEPT
					SELECT DISTINCT TGDT2.MAGV, TGDT2.MADT
					FROM GIAOVIEN GV1, THAMGIADT TGDT1, THAMGIADT TGDT2
					WHERE TGDT1.MADT = TGDT2.MADT AND GV1.MAGV = TGDT1.MAGV AND GV1.HOTEN = N'Trần Hà Hương'
					) AS TBL WHERE TBL.MAGV = KQ.MAGV) AND KQ.HOTEN != N'Trần Hà Hương'

--Q63 Cho biết tên đề tài nào mà được tất cả giáo viên của bộ môn Hoá Hữu Cơ tham gia
SELECT KQ.TENDT
FROM DETAI KQ JOIN THAMGIADT BC ON BC.MADT = KQ.MADT
WHERE BC.MAGV IN (SELECT MAGV 
                  FROM GIAOVIEN C JOIN BOMON BM ON C.MABM = BM.MABM
                  WHERE BM.TENBM = N'Hóa hữu cơ')
GROUP BY KQ.TENDT
HAVING COUNT (DISTINCT MAGV) = (SELECT COUNT(*)
                                FROM GIAOVIEN C JOIN BOMON BM ON C.MABM = BM.MABM
                                WHERE BM.TENBM = N'Hóa hữu cơ')

--Q64 Cho biết tên giáo viên nào mà tham gia được tất cả các công việc của đề tài 006
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
WHERE TGDT.MADT = '006'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(TGDT.STT) = (SELECT COUNT(SOTT) FROM CONGVIEC WHERE MADT = '006')

--Q65 Cho biết tên giáo viên nào thàm gia tất cả các đề tài của chủ đề Ứng dụng công nghệ
SELECT GV.HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT MADT FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD WHERE CD.TENCD = N'Ứng dụng công nghệ'
					EXCEPT
					SELECT MADT FROM THAMGIADT TGDT WHERE TGDT.MAGV = GV.MAGV)

--Q66 Cho biết tên các giáo viên nào tham gia các đề tài mà do Trần Trà Hương làm chủ nhiệm
SELECT GV.HOTEN
FROM GIAOVIEN GV 
WHERE NOT EXISTS (SELECT MADT FROM DETAI DT JOIN GIAOVIEN GV2 ON DT.GVCNDT = GV2.MAGV WHERE GV2.HOTEN = N'Trần Trà Hương'
					EXCEPT
					SELECT MADT FROM THAMGIADT TGDT WHERE TGDT.MAGV = GV.MAGV)

--67. CHO BIẾT TÊN ĐỀ TÀI MÀ TẤT CẢ GV KHOA CNTT THAM GIA
--KQ: DETAI(MADT)
--C:GIAOVIEN , BOMON(MAGV)
--BC:THAMGIADT (MADT, MAGV)
SELECT KQ.*
FROM DETAI KQ
WHERE NOT EXISTS (SELECT C.MAGV
				  FROM GIAOVIEN C JOIN BOMON BM ON BM.MABM = C.MABM
				  WHERE BM.MAKHOA = 'CNTT'
				  EXCEPT
				  SELECT BC.MAGV
				  FROM THAMGIADT BC
				  WHERE BC.MADT = KQ.MADT)
SELECT KQ.MADT,COUNT(DISTINCT MAGV)
FROM DETAI KQ JOIN THAMGIADT BC ON BC.MADT = KQ.MADT
WHERE BC.MAGV IN (SELECT MAGV 
				  FROM GIAOVIEN C JOIN BOMON BM ON
				  BM.MABM = C.MABM
				  WHERE BM.MAKHOA = 'CNTT')
GROUP BY KQ.MADT
HAVING COUNT(DISTINCT MAGV) = (SELECT COUNT(*)
								FROM GIAOVIEN C JOIN BOMON BM ON
								BM.MABM = C.MABM
								WHERE BM.MAKHOA = 'CNTT')


--Q68 Cho biết tên giáo viên nào tham gia tất cả các công việc của đề tài nghiên cứu tế bào gốc
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
WHERE TGDT.MADT = (SELECT MADT FROM CHUDE WHERE TENCD = N'Nghiên cứu tế bào gốc')
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(TGDT.STT) = (SELECT COUNT(SOTT) FROM CONGVIEC WHERE MADT = 
					(SELECT MADT FROM CHUDE WHERE TENCD = N'Nghiên cứu tế bào gốc'))

--Q69 Tìm tên các giáo viên được phân công làm tất cả các đề tài có kinh phí trên 100 triệu
SELECT GV.*
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT DT.MADT FROM DETAI DT WHERE DT.KINHPHI > 100
					EXCEPT 
					SELECT TGDT.MADT FROM THAMGIADT TGDT WHERE GV.MAGV = TGDT.MAGV)

--Q70 Cho biết tên đề tài nào mà được tất cả các giáo viên khoa sinh học tham gia
SELECT DT.TENDT
FROM DETAI DT JOIN THAMGIADT TGDT ON TGDT.MADT = DT.MADT
WHERE TGDT.MAGV IN (SELECT GV.MAGV 
                  FROM GIAOVIEN  GV JOIN BOMON BM ON GV.MABM = BM.MABM JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
                  WHERE K.TENKHOA = N'Sinh học')
GROUP BY DT.TENDT
HAVING COUNT (DISTINCT MAGV) = (SELECT COUNT(*)
                                FROM GIAOVIEN  GV JOIN BOMON BM ON GV.MABM = BM.MABM JOIN KHOA K ON K.MAKHOA = BM.MAKHOA
								WHERE K.TENKHOA = N'Sinh học')

--Q71 Cho biết mã số, họ tên, ngày sinh của giáo viên tham gia tất cả các công việc của để tài "Ứng dụng hoá học xanh"
SELECT GV.MAGV, GV.HOTEN, GV.NGSINH
FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
WHERE TGDT.MADT = (SELECT MADT FROM DETAI WHERE TENDT = N'Ứng dụng hoá học xanh')
GROUP BY GV.MAGV, GV.HOTEN, GV.NGSINH
HAVING COUNT(TGDT.STT) = (SELECT COUNT(SOTT) FROM CONGVIEC WHERE MADT = (SELECT MADT FROM DETAI WHERE TENDT = N'Ứng dụng hoá học xanh'))

--Q72 Cho biết mã số, họ tên, tên bộ môn và tên người quản lý chuyên môn 
--của giáo viên tham gia tất cả các đề tài thuộc chủ đề "Nghiên cứu phát triển"
SELECT GV1.MAGV, GV1.HOTEN, GV2.HOTEN
FROM GIAOVIEN GV1 JOIN BOMON BM ON GV1.MABM = BM.MABM 
JOIN GIAOVIEN GV2 ON GV1.MAGV = GV2.GVQLCM 
JOIN THAMGIADT TGDT ON GV1.MAGV = TGDT.MAGV
WHERE TGDT.MADT = (SELECT MADT FROM CHUDE WHERE TENCD = N'Nghiên cứu phát triển')
GROUP BY GV1.MAGV, GV1.HOTEN, GV2.HOTEN
HAVING COUNT(TGDT.STT) = (SELECT COUNT(SOTT) FROM CONGVIEC WHERE MADT = 
					(SELECT MADT FROM CHUDE WHERE TENCD = N'Nghiên cứu phát triển'))
