-- MSSV: 21127511
-- MALOP: 21CLC02

USE master
GO

USE QLDTAI

-- Q35: CHO BIẾT MỨC LƯƠNG CAO NHẤT CỦA CÁC GIẢNG VIÊN 

SELECT DISTINCT MAX(GV.LUONG) AS N'MỨC LƯƠNG CAO NHẤT'
FROM GIAOVIEN GV


-- Q36: CHO VIẾT NHỮNG GIÁO VIÊN CÓ LƯƠNG LỚN NHẤT

SELECT GV.HOTEN AS N'HỌ VÀ TÊN ', GV.LUONG AS N'MỨC LƯƠNG'
FROM GIAOVIEN GV
WHERE (SELECT COUNT(*)
FROM GIAOVIEN GV2
WHERE GV2.LUONG > GV.LUONG) = 0

-- Q37:CHO BIẾT LƯƠNG CAO NHẤT TRONG BỘ MÔN 'HTTT'

SELECT GV.HOTEN AS N'HỌ VÀ TÊN ', GV.LUONG AS N'LƯƠNG CAO NHẤT'
FROM GIAOVIEN GV
WHERE (SELECT COUNT(*)
FROM GIAOVIEN GV2
WHERE GV2.LUONG > GV.LUONG) = 0 AND GV.MABM = 'HTTT'

-- Q38: CHO BIẾT TÊN GIÁO VIÊN LỚN TUỔI NHẤT CỦA BỘ MÔN 'HỆ THỐNG THÔNG TIN'

SELECT GV.HOTEN AS N'HỌ VÀ TÊN'
FROM GIAOVIEN GV, BOMON BM
WHERE YEAR(GV.NGSINH) = (SELECT YEAR(MIN(GV2.NGSINH)) 
FROM GIAOVIEN GV2, BOMON BM
WHERE BM.TENBM = N'Hệ thống thông tin' AND BM.MABM = GV2.MABM) AND BM.TENBM = N'Hệ thống thông tin'

-- Q39: CHO BIẾT TÊN GIÁO VIÊN NHỎ TUỔI NHẤT KHOA CÔNG NGHỆ THÔNG TIN

SELECT GV.HOTEN AS N'HỌ VÀ TÊN'
FROM GIAOVIEN GV, BOMON BM, KHOA KH
WHERE YEAR(GV.NGSINH) = 
(
	SELECT YEAR(MAX(GV2.NGSINH)) 
	FROM GIAOVIEN GV2, BOMON BM, KHOA KH
	WHERE BM.MABM = GV2.MABM AND BM.MAKHOA = KH.MAKHOA AND KH.TENKHOA = N'Công nghệ thông tin'
)
AND BM.MAKHOA = KH.MAKHOA AND KH.TENKHOA = N'Công nghệ thông tin' AND GV.MABM = BM.MABM

-- Q40: CHO BIẾT TÊN GIÁO VIÊN VÀ TÊN KHOA CỦA GIÁO VIÊN CÓ LƯƠNG CAO NHẤT

SELECT GV.HOTEN AS N'HỌ VÀ TÊN', KH.TENKHOA AS N'TÊN KHOA'
FROM GIAOVIEN GV, BOMON BM, KHOA KH
WHERE BM.MABM = GV.MABM AND KH.MAKHOA = BM.MAKHOA AND GV.LUONG = 
(
	SELECT MAX(GV.LUONG)
	FROM GIAOVIEN GV
)

-- Q41: CHO BIẾT NHỮNG GIÁO VIÊN CÓ LƯƠNG LỚN NHẤT TRONG BỘ MÔN CỦA HỌ 

SELECT GV.HOTEN N'HỌ VÀ TÊN', BM.TENBM N'BỘ MÔN'
FROM GIAOVIEN GV, BOMON BM
WHERE EXISTS
(
	SELECT * 
	FROM(
		SELECT GV.MABM, MAX(GV.LUONG) AS LUONG
		FROM GIAOVIEN GV
		GROUP BY GV.MABM
	) AS TEMP
	WHERE GV.LUONG = TEMP.LUONG
) AND BM.MABM = GV.MABM

-- Q42: CHO BIẾT TÊN NHỮNG ĐỀ TÀI MÀ GIÁO VIÊN NGUYỄN HOÀI AN CHƯA THAM GIA 

SELECT DISTINCT DT.TENDT AS N'TÊN ĐỀ TÀI CHƯA THAM GIA'
FROM DETAI DT
WHERE DT.MADT NOT IN
(
	SELECT DISTINCT TGDT2.MADT
	FROM THAMGIADT TGDT2, GIAOVIEN GV2
	WHERE GV2.MAGV = TGDT2.MAGV AND GV2.HOTEN = N'Nguyễn Hoài An'
)

-- Q43: CHO BIẾT NHỮNG ĐỀ TÀI MÀ GIÁO VIÊN NGUYỄN HOÀI AN CHƯA THAM GIA. XUẤT RA TÊN ĐỀ TÀI, TÊN NGƯỜI CHỦ NHIỆM ĐỀ TÀI

SELECT DISTINCT DT.MADT AS N'MÃ ĐỀ TÀI', DT.TENDT AS N'TÊN ĐỀ TÀI CHƯA THAM GIA', GV.HOTEN AS N'GVCNDT'
FROM DETAI DT, GIAOVIEN GV
WHERE DT.MADT NOT IN
(
	SELECT DISTINCT TGDT2.MADT
	FROM THAMGIADT TGDT2, GIAOVIEN GV2
	WHERE GV2.MAGV = TGDT2.MAGV AND GV2.HOTEN = N'Nguyễn Hoài An'
) AND DT.GVCNDT = GV.MAGV

-- Q44: CHO BIẾT TÊN NHỮNG GIÁO VIÊN KHOA CÔNG NGHỆ THÔNG TIN MÀ CHƯA THAM GIA ĐỀ TÀI NÀO

SELECT GV.HOTEN AS N'GIÁO VIÊN CNTT CHƯA TGDT'
FROM GIAOVIEN GV, KHOA KH, BOMON BM
WHERE GV.MAGV NOT IN 
(
	SELECT DISTINCT TGDT.MAGV
	FROM THAMGIADT TGDT
) AND KH.TENKHOA = N'Công nghệ thông tin' AND BM.MABM = GV.MABM AND KH.MAKHOA = BM.MAKHOA

-- Q45:TÌM NHỮNG GIÁO VIÊN KHÔNG THAM GIA BẤT CỨ ĐỀ TÀI NÀO

SELECT GV.HOTEN AS N'GIÁO VIÊN KHÔNG TGDT'
FROM GIAOVIEN GV
WHERE GV.MAGV NOT IN 
(
	SELECT DISTINCT TGDT.MAGV
	FROM THAMGIADT TGDT
)
