-- MSSV: 21127511
-- MALOP: 21CLC02

USE master
GO

USE QLDTAI

-- Q35: CHO BIẾT MỨC LƯƠNG CAO NHẤT CỦA CÁC GIẢNG VIÊN 

SELECT DISTINCT MAX(GV.LUONG) AS N'MỨC LƯƠNG CAO NHẤT'
FROM GIAOVIEN GV


-- Q36: CHO VIẾT NHỮNG GIÁO VIÊN CÓ LƯƠNG LỚN NHẤT

SELECT GV.HOTEN AS N'HỌ VÀ TÊN ', GV.LUONG AS N'MỨC LƯƠNG'
FROM GIAOVIEN GV
WHERE (SELECT COUNT(*)
FROM GIAOVIEN GV2
WHERE GV2.LUONG > GV.LUONG) = 0

-- Q37:CHO BIẾT LƯƠNG CAO NHẤT TRONG BỘ MÔN 'HTTT'

SELECT GV.HOTEN AS N'HỌ VÀ TÊN ', GV.LUONG AS N'LƯƠNG CAO NHẤT'
FROM GIAOVIEN GV
WHERE (SELECT COUNT(*)
FROM GIAOVIEN GV2
WHERE GV2.LUONG > GV.LUONG) = 0 AND GV.MABM = 'HTTT'

-- Q38: CHO BIẾT TÊN GIÁO VIÊN LỚN TUỔI NHẤT CỦA BỘ MÔN 'HỆ THỐNG THÔNG TIN'

SELECT GV.HOTEN AS N'HỌ VÀ TÊN'
FROM GIAOVIEN GV, BOMON BM
WHERE YEAR(GV.NGSINH) = (SELECT YEAR(MIN(GV2.NGSINH)) 
FROM GIAOVIEN GV2, BOMON BM
WHERE BM.TENBM = N'Hệ thống thông tin' AND BM.MABM = GV2.MABM) AND BM.TENBM = N'Hệ thống thông tin'

-- Q39: CHO BIẾT TÊN GIÁO VIÊN NHỎ TUỔI NHẤT KHOA CÔNG NGHỆ THÔNG TIN

SELECT GV.HOTEN AS N'HỌ VÀ TÊN'
FROM GIAOVIEN GV, BOMON BM, KHOA KH
WHERE YEAR(GV.NGSINH) = 
(
	SELECT YEAR(MAX(GV2.NGSINH)) 
	FROM GIAOVIEN GV2, BOMON BM, KHOA KH
	WHERE BM.MABM = GV2.MABM AND BM.MAKHOA = KH.MAKHOA AND KH.TENKHOA = N'Công nghệ thông tin'
)
AND BM.MAKHOA = KH.MAKHOA AND KH.TENKHOA = N'Công nghệ thông tin' AND GV.MABM = BM.MABM

-- Q40: CHO BIẾT TÊN GIÁO VIÊN VÀ TÊN KHOA CỦA GIÁO VIÊN CÓ LƯƠNG CAO NHẤT

SELECT GV.HOTEN AS N'HỌ VÀ TÊN', KH.TENKHOA AS N'TÊN KHOA'
FROM GIAOVIEN GV, BOMON BM, KHOA KH
WHERE BM.MABM = GV.MABM AND KH.MAKHOA = BM.MAKHOA AND GV.LUONG = 
(
	SELECT MAX(GV.LUONG)
	FROM GIAOVIEN GV
)

-- Q41: CHO BIẾT NHỮNG GIÁO VIÊN CÓ LƯƠNG LỚN NHẤT TRONG BỘ MÔN CỦA HỌ 

SELECT GV.HOTEN N'HỌ VÀ TÊN', BM.TENBM N'BỘ MÔN'
FROM GIAOVIEN GV, BOMON BM
WHERE EXISTS
(
	SELECT * 
	FROM(
		SELECT GV.MABM, MAX(GV.LUONG) AS LUONG
		FROM GIAOVIEN GV
		GROUP BY GV.MABM
	) AS TEMP
	WHERE GV.LUONG = TEMP.LUONG
) AND BM.MABM = GV.MABM

-- Q42: CHO BIẾT TÊN NHỮNG ĐỀ TÀI MÀ GIÁO VIÊN NGUYỄN HOÀI AN CHƯA THAM GIA 

SELECT DISTINCT DT.TENDT AS N'TÊN ĐỀ TÀI CHƯA THAM GIA'
FROM DETAI DT
WHERE DT.MADT NOT IN
(
	SELECT DISTINCT TGDT2.MADT
	FROM THAMGIADT TGDT2, GIAOVIEN GV2
	WHERE GV2.MAGV = TGDT2.MAGV AND GV2.HOTEN = N'Nguyễn Hoài An'
)

-- Q43: CHO BIẾT NHỮNG ĐỀ TÀI MÀ GIÁO VIÊN NGUYỄN HOÀI AN CHƯA THAM GIA. XUẤT RA TÊN ĐỀ TÀI, TÊN NGƯỜI CHỦ NHIỆM ĐỀ TÀI

SELECT DISTINCT DT.MADT AS N'MÃ ĐỀ TÀI', DT.TENDT AS N'TÊN ĐỀ TÀI CHƯA THAM GIA', GV.HOTEN AS N'GVCNDT'
FROM DETAI DT, GIAOVIEN GV
WHERE DT.MADT NOT IN
(
	SELECT DISTINCT TGDT2.MADT
	FROM THAMGIADT TGDT2, GIAOVIEN GV2
	WHERE GV2.MAGV = TGDT2.MAGV AND GV2.HOTEN = N'Nguyễn Hoài An'
) AND DT.GVCNDT = GV.MAGV

-- Q44: CHO BIẾT TÊN NHỮNG GIÁO VIÊN KHOA CÔNG NGHỆ THÔNG TIN MÀ CHƯA THAM GIA ĐỀ TÀI NÀO

SELECT GV.HOTEN AS N'GIÁO VIÊN CNTT CHƯA TGDT'
FROM GIAOVIEN GV, KHOA KH, BOMON BM
WHERE GV.MAGV NOT IN 
(
	SELECT DISTINCT TGDT.MAGV
	FROM THAMGIADT TGDT
) AND KH.TENKHOA = N'Công nghệ thông tin' AND BM.MABM = GV.MABM AND KH.MAKHOA = BM.MAKHOA

-- Q45:TÌM NHỮNG GIÁO VIÊN KHÔNG THAM GIA BẤT CỨ ĐỀ TÀI NÀO

SELECT GV.HOTEN AS N'GIÁO VIÊN KHÔNG TGDT'
FROM GIAOVIEN GV
WHERE GV.MAGV NOT IN 
(
	SELECT DISTINCT TGDT.MAGV
	FROM THAMGIADT TGDT
)

-- Q46: CHO BIẾT GIÁO VIÊN CÓ LƯƠNG LỚN HƠN LƯƠNG CỦA GIÁO VIÊN 'NGUYỄN HOÀI AN'

SELECT GV.HOTEN AS N'GIÁO VIÊN LƯƠNG CAO HƠN NGUYỄN HOÀI AN', GV.LUONG AS N'LƯƠNG'
FROM GIAOVIEN GV
WHERE GV.LUONG >
(
	SELECT GV2.LUONG
	FROM GIAOVIEN GV2
	WHERE GV2.HOTEN = N'Nguyễn Hoài An'
)

-- Q47: TÌM NHỮNG TRƯỞNG BỘ MÔN THAM GIA TỐI THIỂU 1 ĐỀ TÀI

SELECT DISTINCT BM.TRUONGBM AS N'TRƯỞNG BM THAM GIA TỐI THIỂU 1 ĐỀ TÀI'
FROM BOMON BM, THAMGIADT TGDT
WHERE BM.TRUONGBM IS NOT NULL AND EXISTS 
(
	SELECT DISTINCT TGDT.MAGV
	FROM THAMGIADT TGDT
) AND BM.TRUONGBM = TGDT.MAGV

-- Q48: TÌM GIÁO VIÊN TRÙNG TÊN VÀ CÙNG GIỚI TÍNH VỚI GIÁO VIÊN KHÁC TRONG BỘ MÔN

SELECT GV1.HOTEN N'GIÁO VIÊN CÓ TÊN TRÙNG VÀ CÙNG GIỚI TÍNH TRONG CÙNG BM'
FROM GIAOVIEN GV1, GIAOVIEN GV2
WHERE GV1.HOTEN = GV2.HOTEN AND GV1.PHAI = GV2.PHAI AND GV1.MAGV != GV2.MAGV AND GV1.MABM = GV2.MABM

-- Q49: TÌM NHỮNG GIÁO VIÊN CÓ LƯƠNG LỚN HƠN LƯƠNG CỦA ÍT NHẤT MỘT GIÁO VIÊN BỘ MÔN 'CÔNG NGHỆ PHẦN MỀM'

SELECT *
FROM GIAOVIEN GV
WHERE GV.LUONG > ANY 
(
	SELECT GV1. LUONG
	FROM GIAOVIEN GV1, BOMON BM
	WHERE GV1.MABM = BM.MABM AND BM.TENBM = N'Công nghệ phần mềm'
)

-- Q50: TÌM NHỮNG GIÁO VIÊN CÓ LƯƠNG LỚN HƠN LƯƠNG CỦA TẤT CẢ GIÁO VIÊN THUỘC BỘ MÔN 'HỆ THÔNG THÔNG TIN'

SELECT *
FROM GIAOVIEN GV
WHERE GV.LUONG > ALL 
(
	SELECT GV1. LUONG
	FROM GIAOVIEN GV1, BOMON BM
	WHERE GV1.MABM = BM.MABM AND BM.TENBM = N'Hệ thống thông tin'
)
-- Q51. Cho biết tên khoa có đông giáo viên nhất

SELECT K.TENKHOA AS N'TÊN KHOA ĐÔNG GIÁO VIÊN NHẤT'
FROM KHOA K
WHERE K.MAKHOA IN
(
  SELECT TOP 1 BM.MAKHOA
  FROM BOMON BM
  JOIN GIAOVIEN GV ON BM.MABM = GV.MABM
  GROUP BY BM.MAKHOA
  ORDER BY COUNT(GV.MAGV) DESC
);

-- Q52. Cho biết họ tên giáo viên chủ nhiệm nhiều đề tài nhất

SELECT GV.HOTEN AS N'HỌ VÀ TÊN'
FROM GIAOVIEN GV
WHERE GV.MAGV IN
(
  SELECT GV1.MAGV
  FROM DETAI DT
  JOIN GIAOVIEN GV1 ON DT.GVCNDT = GV1.MAGV
  GROUP BY GV1.MAGV
  HAVING COUNT(DT.MADT) >= ALL
  (
    SELECT COUNT(DT1.MADT)
    FROM DETAI DT1
    JOIN GIAOVIEN GV2 ON DT1.GVCNDT = GV2.MAGV
    GROUP BY GV2.MAGV
  )
)


-- Q53. Cho biết mã bộ môn có nhiều giáo viên nhất

SELECT BM1.MABM
FROM BOMON BM1, GIAOVIEN GV
WHERE BM1.MABM = GV.MABM
GROUP BY BM1.MABM
HAVING COUNT(GV.MAGV) >= ALL
(
	SELECT COUNT(GV1.MAGV)
	FROM GIAOVIEN GV1, BOMON BM2
	WHERE GV1.MABM = BM2.MABM
	GROUP BY BM2.MABM
)

-- Q54. Cho biết tên giáo viên và tên bộ môn của giáo viên tham gia nhiều đề tài nhất.

SELECT DISTINCT GV.HOTEN AS N'HỌ VÀ TÊN', BM.TENBM AS N'TÊN BỘ MÔN'
FROM GIAOVIEN GV
JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV
JOIN BOMON BM ON GV.MABM = BM.MABM
WHERE GV.MAGV IN
(
  SELECT GV1.MAGV
  FROM THAMGIADT TGDT1
  JOIN GIAOVIEN GV1 ON TGDT1.MAGV = GV1.MAGV
  GROUP BY GV1.MAGV
  HAVING COUNT(TGDT1.MADT) >= ALL
  (
    SELECT COUNT(TGDT2.MADT)
    FROM THAMGIADT TGDT2
    JOIN GIAOVIEN GV2 ON TGDT2.MAGV = GV2.MAGV
    GROUP BY GV2.MAGV
  )
)

--Q55. Cho biết tên giáo viên tham gia nhiều đề tài nhất của bộ môn HTTT.
select gv.HOTEN
from GIAOVIEN gv join THAMGIADT tg on gv.MAGV = tg.MAGV
where gv.MABM = N'HTTT'
group by gv.HOTEN, gv.MAGV
having count(*) >= all(select count(*)
                        from GIAOVIEN gv join THAMGIADT tg on gv.MAGV = tg.MAGV
                        where gv.MABM = N'HTTT'
                        group by gv.HOTEN, gv.MAGV)

--Q56. Cho biết tên giáo viên và tên bộ môn của giáo viên có nhiều người thân nhất.
select gv.HOTEN, bm.TENBM
from GIAOVIEN gv join BOMON bm on gv.MABM = bm.MABM
join NGUOITHAN nt on gv.MAGV = nt.MAGV
group by gv.HOTEN, gv.MAGV, bm.TENBM
having count(*) >= all(select count(*)
                        from GIAOVIEN gv join BOMON bm on gv.MABM = bm.MABM
                        join NGUOITHAN nt on gv.MAGV = nt.MAGV
                        group by gv.HOTEN, gv.MAGV, bm.TENBM)

--Q57. Cho biết tên trưởng bộ môn mà chủ nhiệm nhiều đề tài nhất.
select gv.HOTEN
from GIAOVIEN gv join BOMON bm on gv.MAGV = bm.TRUONGBM
join DETAI dt on gv.MAGV = dt.GVCNDT
group by gv.HOTEN, gv.MAGV
having count(*) >= all(select count(*)
                        from GIAOVIEN gv join BOMON bm on gv.MAGV = bm.TRUONGBM
                        join DETAI dt on gv.MAGV = dt.GVCNDT
                        group by gv.HOTEN, gv.MAGV)