-- MSSV: 21127511
-- MALOP: 21CLC02

USE QLDTAI

--Q1
SELECT HOTEN, LUONG FROM GIAOVIEN
WHERE PHAI = N'Nữ'


--Q3
SELECT MAGV
FROM GIAOVIEN GV
WHERE HOTEN LIKE N'Nguyễn%' and LUONG > 2000
UNION
SELECT TRUONGBM FROM BOMON
WHERE TRUONGBM IS NOT NULL AND YEAR(NGAYNHANCHUC) > 1995

--Q5
SELECT * FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM


--Q7
SELECT TENDT AS N'ĐỀ TÀI', HOTEN AS N'GIÁO VIÊN CHỦ NHIỆM ĐỀ TÀI'
FROM DETAI JOIN GIAOVIEN
ON DETAI.GVCNDT = GIAOVIEN.MAGV

--Q9 
SELECT GV.MAGV as N'GIÁO VIÊN BỘ MÔN VI SINH THAM GIA ĐỀ TÀI 006'
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TENBM = 'VI SINH' AND GV.MABM = BM.MABM
UNION
SELECT GV.MAGV
FROM GIAOVIEN GV, THAMGIADT TGDT
WHERE TGDT.MADT = '006' and TGDT.MAGV = GV.MAGV

--Q11
SELECT GV.HOTEN AS N'GIÁO VIÊN', GVQLCM.HOTEN AS N'NGƯỜI PHỤ TRÁCH CHUYÊN MÔN TRỰC TIẾP'
FROM GIAOVIEN GV, GIAOVIEN GVQLCM
WHERE GV.GVQLCM = GVQLCM.MAGV

--Q13
SELECT GIAOVIEN.HOTEN AS N'TRƯỞNG BỘ MÔN HỆ THỐNG THÔNG TIN'
FROM GIAOVIEN, BOMON
WHERE BOMON.TRUONGBM = MAGV AND BOMON.TENBM = N'Hệ thống thông tin'

--Q15
SELECT CV.TENCV AS N'TÊN CÁC CÔNG VIỆC CỦA ĐỀ TÀI HTTT'
FROM CONGVIEC CV, DETAI DT
WHERE DT.TENDT = N'HTTT quản lý các trường ĐH' AND DT.MADT = CV.MADT AND DATEPART(YEAR, CV.NGAYBD) = 2008 AND DATEPART(MONTH, CV.NGAYBD) = 3

--Q17
SELECT CV.TENCV 
FROM CONGVIEC CV
WHERE CV.NGAYBD >= '2007-01-01' AND CV.NGAYBD <= '2007-08-01'

--Q19 
SELECT GV.MAGV AS N'GIÁO VIÊN VỪA LÀ TRƯỞNG BỘ MÔN VÙA CHỦ NHIỆM ĐỀ TÀI'
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TRUONGBM = GV.MAGV 
UNION
SELECT GV.MAGV
FROM GIAOVIEN GV, DETAI DT
WHERE GV.MAGV = DT.GVCNDT

--Q21
SELECT GV.HOTEN AS N'GIÁO VIÊN VỪA LÀ TRƯỞNG BỘ MÔN VÙA CHỦ NHIỆM ĐỀ TÀI'
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TRUONGBM = GV.MAGV 
UNION
SELECT HOTEN
FROM GIAOVIEN GV, DETAI DT
WHERE GV.MAGV = DT.GVCNDT

--23
SELECT GV.MAGV
FROM GIAOVIEN GV JOIN THAMGIADT TGDT
ON GV.MABM = 'HTTT' OR (TGDT.MADT = '001' AND GV.MAGV = TGDT.MAGV)
INTERSECT
SELECT MAGV
FROM GIAOVIEN

--Q25
SELECT GIAOVIEN.*, BOMON.TRUONGBM 
FROM GIAOVIEN, BOMON
WHERE BOMON.TRUONGBM = MAGV
