-- MSSV: 21127511
-- MALOP: 21CLC02

USE QLDTAI

--Q2 
SELECT HOTEN, LUONG, LUONG*1.1 AS N'LƯƠNG SAU KHI TĂNG' FROM GIAOVIEN

--Q4
SELECT GV.HOTEN as  N'TÊN CỦA NHỮNG GIÁO VIÊN KHOA CÔNG NGHỆ THÔNG TIN'
FROM KHOA KH, GIAOVIEN GV, BOMON BM
WHERE KH.TENKHOA = N'Công nghệ thông tin' and Bm.MABM = GV.MABM and Bm.MAKHOA = Kh.MAKHOA

--Q6
SELECT Gv.Hoten, Bm.*
FROM GIAOVIEN gv, BOMON bm
where Gv.MABM = bm.MABM

--Q8
SELECT* 
FROM KHOA JOIN GIAOVIEN
ON KHOA.TRUONGKHOA = GIAOVIEN.MAGV

--Q10
SELECT DT.TENDT, CD.TENCD, GV.HOTEN, GV.NGSINH, GV.DIACHI
FROM GIAOVIEN GV, CHUDE CD, DETAI DT, THAMGIADT TGDT
WHERE DT.CAPQL = N'Thành phố' AND DT.MACD = CD.MACD AND TGDT.MAGV = GV.MAGV

--Q12
SELECT GV.HOTEN AS N'GIÁO VIÊN ĐƯỢC NGUYỄN THANH TÙNG PHỤ TRÁCH TRỰC TIẾP'
FROM GIAOVIEN GV, GIAOVIEN GVPTTT
WHERE GV.GVQLCM = GVPTTT.MAGV AND GVPTTT.HOTEN = N'Nguyễn Thanh tùng'

--Q14
SELECT GV.HOTEN as N'GV CHỦ NHIỆM ĐỀ TÀI QUẢN LÝ GIÁO DỤC'
from GIAOVIEN GV, DETAI DT, CHUDE CD
where DT.GVCNDT = GV.MAGV and CD.TENCD = N'Quản lý giáo dục' and DT.MACD = CD.MACD
INTERSECT
SELECT HOTEN
FROM GIAOVIEN

--Q16
SELECT GV.HOTEN AS N'GIÁO VIÊN', GVQLCM.HOTEN AS N'GIÁO VIÊN QUẢN LÝ CHUYÊN MÔN'
FROM GIAOVIEN GV, GIAOVIEN GVQLCM
WHERE GV.GVQLCM = GVQLCM.MAGV

--Q18
SELECT GV.HOTEN AS N'GIÁO VIÊN CÙNG BỘ MÔN VỚI GV TRẦN HÀ HƯƠNG'
FROM GIAOVIEN GV, GIAOVIEN THH
WHERE THH.HOTEN = N'Trần Hà Hương' and THH.MABM = GV.MABM and GV.HOTEN != N'Trần Hà Hương'

--Q20
SELECT GV.HOTEN AS N'GIÁO VIÊN VỪA LÀ TRƯỞNG KHOA VỪA LÀ TRƯỞNG BỘ MÔN'
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TRUONGBM = GV.MAGV
UNION
SELECT HOTEN 
FROM GIAOVIEN GV, KHOA KH
WHERE GV.MAGV = KH.TRUONGKHOA

--Q22
SELECT KH.TRUONGKHOA
FROM KHOA KH, DETAI DT 
WHERE KH.TRUONGKHOA = DT.GVCNDT
INTERSECT
SELECT TRUONGKHOA
FROM KHOA

--24
SELECT GV.HOTEN AS N'GIÁO VIÊN LÀM VIỆC CÙNG BỘ MÔN VỚI GV 002', GV.MAGV
FROM GIAOVIEN GV, GIAOVIEN GV2
WHERE GV.MABM = GV2.MABM AND GV2.MAGV = '002' AND GV.MAGV != '002'

--Q26
SELECT HOTEN, LUONG FROM GIAOVIEN
