-- MSSV: 21127511
-- MALOP: 21CLC02

USE QLDTAI

--Q1
SELECT HOTEN, LUONG FROM GIAOVIEN
WHERE PHAI = N'Nữ'

--Q2 
SELECT HOTEN, LUONG, LUONG*1.1 AS N'LƯƠNG SAU KHI TĂNG' FROM GIAOVIEN

--Q3
SELECT MAGV
FROM GIAOVIEN GV
WHERE HOTEN LIKE N'Nguyễn%' and LUONG > 2000
UNION
SELECT TRUONGBM FROM BOMON
WHERE TRUONGBM IS NOT NULL AND YEAR(NGAYNHANCHUC) > 1995

--Q4
SELECT GV.HOTEN as  N'TÊN CỦA NHỮNG GIÁO VIÊN KHOA CÔNG NGHỆ THÔNG TIN'
FROM KHOA KH, GIAOVIEN GV, BOMON BM
WHERE KH.TENKHOA = N'Công nghệ thông tin' and Bm.MABM = GV.MABM and Bm.MAKHOA = Kh.MAKHOA

--Q5
SELECT * FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM

--Q6
SELECT Gv.Hoten, Bm.*
FROM GIAOVIEN gv, BOMON bm
where Gv.MABM = bm.MABM

--Q7
SELECT TENDT AS N'ĐỀ TÀI', HOTEN AS N'GIÁO VIÊN CHỦ NHIỆM ĐỀ TÀI'
FROM DETAI JOIN GIAOVIEN
ON DETAI.GVCNDT = GIAOVIEN.MAGV

--Q8
SELECT* 
FROM KHOA JOIN GIAOVIEN
ON KHOA.TRUONGKHOA = GIAOVIEN.MAGV

--Q9 
SELECT GV.MAGV as N'GIÁO VIÊN BỘ MÔN VI SINH THAM GIA ĐỀ TÀI 006'
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TENBM = 'VI SINH' AND GV.MABM = BM.MABM
UNION
SELECT GV.MAGV
FROM GIAOVIEN GV, THAMGIADT TGDT
WHERE TGDT.MADT = '006' and TGDT.MAGV = GV.MAGV

--Q10
SELECT DT.TENDT, CD.TENCD, GV.HOTEN, GV.NGSINH, GV.DIACHI
FROM GIAOVIEN GV, CHUDE CD, DETAI DT, THAMGIADT TGDT
WHERE DT.CAPQL = N'Thành phố' AND DT.MACD = CD.MACD AND TGDT.MAGV = GV.MAGV

--Q11
SELECT GV.HOTEN AS N'GIÁO VIÊN', GVQLCM.HOTEN AS N'NGƯỜI PHỤ TRÁCH CHUYÊN MÔN TRỰC TIẾP'
FROM GIAOVIEN GV, GIAOVIEN GVQLCM
WHERE GV.GVQLCM = GVQLCM.MAGV

--Q12
SELECT GV.HOTEN AS N'GIÁO VIÊN ĐƯỢC NGUYỄN THANH TÙNG PHỤ TRÁCH TRỰC TIẾP'
FROM GIAOVIEN GV, GIAOVIEN GVPTTT
WHERE GV.GVQLCM = GVPTTT.MAGV AND GVPTTT.HOTEN = N'Nguyễn Thanh tùng'

--Q13
SELECT GIAOVIEN.HOTEN AS N'TRƯỞNG BỘ MÔN HỆ THỐNG THÔNG TIN'
FROM GIAOVIEN, BOMON
WHERE BOMON.TRUONGBM = MAGV AND BOMON.TENBM = N'Hệ thống thông tin'

--Q14
SELECT GV.HOTEN as N'GV CHỦ NHIỆM ĐỀ TÀI QUẢN LÝ GIÁO DỤC'
from GIAOVIEN GV, DETAI DT, CHUDE CD
where DT.GVCNDT = GV.MAGV and CD.TENCD = N'Quản lý giáo dục' and DT.MACD = CD.MACD
INTERSECT
SELECT HOTEN
FROM GIAOVIEN

--Q15
SELECT CV.TENCV AS N'TÊN CÁC CÔNG VIỆC CỦA ĐỀ TÀI HTTT'
FROM CONGVIEC CV, DETAI DT
WHERE DT.TENDT = N'HTTT quản lý các trường ĐH' AND DT.MADT = CV.MADT AND DATEPART(YEAR, CV.NGAYBD) = 2008 AND DATEPART(MONTH, CV.NGAYBD) = 3

--Q16
SELECT GV.HOTEN AS N'GIÁO VIÊN', GVQLCM.HOTEN AS N'GIÁO VIÊN QUẢN LÝ CHUYÊN MÔN'
FROM GIAOVIEN GV, GIAOVIEN GVQLCM
WHERE GV.GVQLCM = GVQLCM.MAGV

--Q17
SELECT CV.TENCV 
FROM CONGVIEC CV
WHERE CV.NGAYBD >= '2007-01-01' AND CV.NGAYBD <= '2007-08-01'

--Q18
SELECT GV.HOTEN AS N'GIÁO VIÊN CÙNG BỘ MÔN VỚI GV TRẦN HÀ HƯƠNG'
FROM GIAOVIEN GV, GIAOVIEN THH
WHERE THH.HOTEN = N'Trần Hà Hương' and THH.MABM = GV.MABM and GV.HOTEN != N'Trần Hà Hương'

--Q19 
SELECT GV.MAGV AS N'GIÁO VIÊN VỪA LÀ TRƯỞNG BỘ MÔN VÙA CHỦ NHIỆM ĐỀ TÀI'
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TRUONGBM = GV.MAGV 
UNION
SELECT GV.MAGV
FROM GIAOVIEN GV, DETAI DT
WHERE GV.MAGV = DT.GVCNDT

--Q20
SELECT GV.HOTEN AS N'GIÁO VIÊN VỪA LÀ TRƯỞNG KHOA VỪA LÀ TRƯỞNG BỘ MÔN'
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TRUONGBM = GV.MAGV
UNION
SELECT HOTEN 
FROM GIAOVIEN GV, KHOA KH
WHERE GV.MAGV = KH.TRUONGKHOA

--Q21
SELECT GV.HOTEN AS N'GIÁO VIÊN VỪA LÀ TRƯỞNG BỘ MÔN VÙA CHỦ NHIỆM ĐỀ TÀI'
FROM GIAOVIEN GV, BOMON BM
WHERE BM.TRUONGBM = GV.MAGV 
UNION
SELECT HOTEN
FROM GIAOVIEN GV, DETAI DT
WHERE GV.MAGV = DT.GVCNDT

--Q22
SELECT KH.TRUONGKHOA
FROM KHOA KH, DETAI DT 
WHERE KH.TRUONGKHOA = DT.GVCNDT
INTERSECT
SELECT TRUONGKHOA
FROM KHOA

--23
SELECT GV.MAGV
FROM GIAOVIEN GV JOIN THAMGIADT TGDT
ON GV.MABM = 'HTTT' OR (TGDT.MADT = '001' AND GV.MAGV = TGDT.MAGV)
INTERSECT
SELECT MAGV
FROM GIAOVIEN

--24
SELECT GV.HOTEN AS N'GIÁO VIÊN LÀM VIỆC CÙNG BỘ MÔN VỚI GV 002', GV.MAGV
FROM GIAOVIEN GV, GIAOVIEN GV2
WHERE GV.MABM = GV2.MABM AND GV2.MAGV = '002' AND GV.MAGV != '002'

--Q25
SELECT GIAOVIEN.*, BOMON.TRUONGBM 
FROM GIAOVIEN, BOMON
WHERE BOMON.TRUONGBM = MAGV

--Q26
SELECT HOTEN, LUONG FROM GIAOVIEN
